platform :ios, '10.0'

target 'ChatExample' do
  use_frameworks!
  pod 'MessageKit', :path => '../'
  pod 'MessageInputBar', :git => 'https://github.com/MessageKit/MessageInputBar.git', :branch => 'master'

  pod 'SoundWave', :path => '../VoiceAndKeyboard/SoundWave'

target 'ChatExampleTests' do
  inherit! :search_paths
end

target 'ChatExampleUITests' do
  inherit! :search_paths
end

end
